name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes -qq tox
    - name: Linting
      run: |
        tox -e pep8
    - name: Unit tests
      run: |
        tox -e py36
